// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import selectedController from "./selected_controller"
application.register("selected", selectedController)

const sports = document.querySelectorAll('.clickable');
const selected = []

const toggleActiveClass = (event) => {
  event.currentTarget.classList.toggle('active');
  selected.push(event.currentTarget.innerText)
};

const toggleActiveOnClick = (sport) => {
  sport.addEventListener('click', toggleActiveClass);
  console.log(selected)
};

sports.forEach(toggleActiveOnClick);
