// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)


import selectedController from "./selected_controller"
application.register("selected", selectedController)

const sports = document.querySelectorAll('.clickable');
const selected = []

const toggleActiveClass = (event) => {
    event.currentTarget.classList.toggle('active');
    selected.push(event.currentTarget.innerText)
};

const toggleActiveOnClick = (sport) => {
    sport.addEventListener('click', toggleActiveClass);
    console.log(selected)
};

sports.forEach(toggleActiveOnClick);

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import AnimatedNumber from 'stimulus-animated-number'

application.register('animated-number', AnimatedNumber)

import MapController from "./map_controller"
application.register("map", MapController)

import DisplayMapController from "./displaymap_controller"
application.register("displaymap", DisplayMapController)

const mapstyle = document.querySelector(".mapboxgl-popup-content")
const mapbutton = document.querySelector("#map-btn")


if (mapbutton) {
    mapbutton.addEventListener("click", () => {
        setTimeout(() => {
            console.log(mapstyle)
        }, 2000);
    })
}