// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import DisplayMapController from "./displaymap_controller"
application.register("displaymap", DisplayMapController)

const mapstyle = document.querySelector(".mapboxgl-popup-content")
const mapbutton = document.querySelector("#map-btn")


if(mapbutton){
    mapbutton.addEventListener("click", () => {
      setTimeout(() => {
          console.log(mapstyle)
      }, 2000);
})
}